# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfd0646adff73078a1abbb681af87e167d3dd5555a2bb0552874958adf5e6efac4df3b23a98dd820c377500b61182615d0c375242e6519886d343f833b70dddd

test:
  secret_key_base: 65f838628fc27255e8024e781a330cb7b1124e844d652ef5ff5409027ff9491719f60fc93ac4018484212d6826e80b3b1aec8586b42d7edab8e210b0c38a5bd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
